{% set name = "lixtools" %}
{% set version = "2021.2.21.1" %}
{% set sha256 = "068ea68fbfe1b3e1134ba544046974ee7426a8305574b7c250e526598385b9df" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy
    - openpyxl >=3
    - pandas
    - pillow
    - py4xs
    - python-barcode
    - qrcode
    - xlrd

test:
  imports:
    - lixtools
  commands:
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "plate_label_template.html"))'
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'

about:
  home: https://github.com/NSLS-II-LIX/lixtools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Software tools for data collection/processing at NSLS-II LiX"
