{% set name = "lixtools" %}
{% set version = "2021.8.2.0" %}
{% set sha256 = "b47b2bfd005cfbfb4e5943e4a1bd51c12278eabee547760ac9b3766bb3e68518" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python !=3.9.5
    - pip
  run:
    - python !=3.9.5
    - matplotlib
    - numpy
    - openpyxl >=3
    - pandas
    - pillow
    - py4xs
    - python-barcode
    - qrcode

test:
  imports:
    - lixtools
  commands:
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "plate_label_template.html"))'
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'

about:
  home: https://github.com/NSLS-II-LIX/lixtools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Software tools for data collection/processing at NSLS-II LiX
