{% set name = "lixtools" %}
{% set version = "2021.2.25.0" %}
{% set sha256 = "134f0101d76270f7d28570742dd61c9cd6fe2929469ce9b37d8aa81ba19ebbb6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # TODO: remove this patch once https://github.com/NSLS-II-LIX/lixtools/pull/1 is merged and released.
    - 0001-missing-files.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - numpy
    - openpyxl >=3
    - pandas
    - pillow
    - py4xs
    - python-barcode
    - qrcode

test:
  imports:
    - lixtools
  commands:
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "plate_label_template.html"))'
    - python -c 'import os, pkg_resources; assert os.path.isfile(pkg_resources.resource_filename("lixtools", "template_report.ipynb"))'

about:
  home: https://github.com/NSLS-II-LIX/lixtools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Software tools for data collection/processing at NSLS-II LiX
